### ISSUE TITLE
Postinstall prevents installation as a dependency

### ISSUE THREAD

**Issue by srconne** [esm-bundle/react-dom#152]
The package.json specifies a postinstall which initializes husky.  Upon an npm install this postinstall step triggers husky which attempts to locate a '.git' folder within the node module.  This step fails as it is not a git repo resulting in a failed module installation.
See: https://github.com/typicode/husky/issues/884

**Comment by groundmuffin** [comment]
The same issue here. Trying to install it as a dependency in a lerna monorepo context.

**Comment by TheMcMurder** [comment]
Fixed. Try installing `17.0.2-fix.0`
